name: dailyfairdeal
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_carousel_widget: ^3.1.0
  carousel_slider: ^5.0.0
  intl: ^0.20.1
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  cloud_firestore: ^5.6.4
  firebase_core: ^3.12.0
  http: ^0.13.6
  flutter_polyline_points: ^1.0.0
  flutter_typeahead: ^5.2.0
  google_place: ^0.4.7
  google_places_flutter: ^2.0.9  
  dio: ^5.8.0+1
  google_maps_webservice: ^0.0.19
  location: ^8.0.0
  marquee: ^2.3.0
  permission_handler: ^11.4.0
  shared_preferences: ^2.5.2
  
  


  flutter_secure_storage: ^9.2.2

dev_dependencies:                                                                                                                     
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
